### ISSUE TITLE
Make package compatible with other platforms

### ISSUE THREAD

**Issue by jesusrp98** [prateekmedia/gtk-flutter#2]
Hi I'm the developer of the `flutter_gtk` package, and I really like this package!

The way `gtk` picks the theme from the GNOME DE via the `gsettings` plugin is genious, an incredible feature to build GTK apps with Flutter.

However this comes with a huge downside: no other platform is supported, apart from Linux.

What I think I'd build is some sort of 'default' theme (maybe light & dark), for when the app runs in an environment where no GTK config file is available. You can easily download the adwaita `css` files and place them inside the project, and use them when needed.

Let me know what you think :)

**Comment by prateekmedia** [comment]
Hi, thanks for making `flutter_gtk`, I started this project after seeing issues and drawbacks on your package.

Anyways, Why not just use the colours from that css file and paste them inside dart code instead of placing a css as an asset?

**Comment by liamdiprose** [comment]
I'm running Linux and this package is working well - thanks @prateekmedia!. But say I want to send my app to a friend on Windows who doesn't have my `gtk.css` file, or `GSettings`, or `xdgdir`. If users could point [gtk_colors.dart](https://github.com/prateekmedia/gtk-flutter/blob/main/lib/src/utils/gtk_colors.dart) to a CSS Asset within their application, your package would run on every platform supported by flutter. 

Regarding your question; you could hardcode a fallback GTK theme that other platforms use, but why? You don't know what theme users want to use, so let them decide, and make it as easy as possible for them to do so. 

@jesusrp98's `flutter_gtk` hard codes the theme/colours, whereas you're the CSS parser-master! There's benefits to both approaches, so make your approach as good as it can be.

**Comment by prateekmedia** [comment]
@liamdiprose I understand you, I have already kept a fallback theme as Adwaita. You can check it here
https://github.com/prateekmedia/gtk-flutter/blob/26e78ba083de9c6b0f2e7d6e010980e56bfb7e82/lib/src/utils/gtk_colors.dart#L117

But I have not tested it, so idk.

**Comment by MalcolmMielle** [comment]
I think the way theming works should be documented somewhere because it can be a little confusing.
I think one problem currently is that the GnomeTheme is reloaded everytime, and we use either the GnomeTheme or we create a Map to the default adwaita theme. I think this package could use only GnomeTheme and populate it with Adwaita default if the gtk.css file is not found.

Then gtk-flutter could provider a Provider of theme as such:

```
import 'package:flutter/material.dart';
import 'package:gtk/gtk.dart';

class GnomeThemeProvider extends ChangeNotifier {
  GnomeTheme theme = GnomeTheme();

  // Constructor
  GnomeThemeProvider() {
    theme.loadFromFile();
    theme.parse();
  }
}
```

That can be used to theme the gtk elements, but even the non-gtk elements:

```
import 'gnome_elements/theme/gnome_theme_provider.dart';

class MyDesktopApp extends StatelessWidget {
  MyDesktopApp();

  @override
  Widget build(BuildContext context) {
    print("Building desktop app");
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      routes: {
        // When navigating to the "/" route, build the FirstScreen widget.
        '/': (context) => DashboardScreen(),
      },
      theme: Provider.of<GnomeThemeProvider>(context).theme.data(context),
      darkTheme: ThemeData(
        brightness: Brightness.dark,
      ),
    );
  }
}
```
This way the programmer doesn't have to specify the theme (adwaita / system) for each element since it is provided directly through the theme.

**Comment by prateekmedia** [comment]
@MalcolmMielle you are right. Would you mind creating a PR?

**Comment by MalcolmMielle** [comment]
I don't have time to do it right now but if I end up doing it I will.

**Comment by prateekmedia** [comment]
@MalcolmMielle Ok I will add it myself then, but can you please test the new version as it includes GSettings v0.2.0 and it requires await to listen for value from GSettings.

If you can fix the theme is not initialized error then it would be great.

Currently I added it's default value as empty string, but still if I access ThemeData then it would return value based on the empty theme instead of the actual theme.

**Comment by MalcolmMielle** [comment]
I'm not sure what the "theme is not init" error is. If you push some changes on a test branch, I'll be happy to test it on my project.

**Comment by MalcolmMielle** [comment]
Just tested your last changes and it did break the code snippet I put above.

**Comment by MalcolmMielle** [comment]
I should send a PR that does that for some elements and you can complete it for the others.

**Comment by prateekmedia** [comment]
We are now using libadwaita design language which doesn't required picking themes from system, So this package is now compatible with any platform from v1.

**Comment by MalcolmMielle** [comment]
Yay to libadwaita. However, we will still need to [read the theme from system using gsettings](https://blogs.gnome.org/alexm/category/libadwaita/). I hope to port this into flutter engine directly, but we may have to do it here also.

**Comment by prateekmedia** [comment]
@MalcolmMielle I have already made an issue there: https://github.com/flutter/flutter/issues/92261

**Comment by MalcolmMielle** [comment]
Super!
