### ISSUE TITLE
Change licence to MIT

### ISSUE THREAD

**Issue by MalcolmMielle** [prateekmedia/gtk-flutter#6]
Would you be ok with changing the license to MIT? The obligation to release the source associated with GPL3 might be a problem for some users and reduce the reach of the library.

**Comment by MalcolmMielle** [comment]
Ho wait I just saw it's the "lesser" GPL license. No problems then although MIT might still be good for this project :)

**Comment by prateekmedia** [comment]
I am thinking to keeping it as LGPL v3 as it doesn't restrict anyone to use this on any type of project and if someone fixes something then they would have to file a PR or publish their changes online due to LGPL which will help this project anyhow.

**Comment by MalcolmMielle** [comment]
Sure that's fine.
