### ISSUE TITLE
Update components to use provider instead of theme enum

### ISSUE THREAD

**Issue by MalcolmMielle** [prateekmedia/gtk-flutter#7]
Buttons, and pop ups need to be updated to use provider so that the layers of enums in gtk_colors can be removed and each element is consistent with the theming :)

**Comment by prateekmedia** [comment]
I don't know much but why not are we dependent on provider, let's say if someone want to use riverpod instead then they would got extra dependency of provider?

I am saying this cause I prefer riverpod.

**Comment by MalcolmMielle** [comment]
I've used both and I think they are both nice. If you want to switch it to riverpod that's fine by me but the PR I sent was using provider :). Now the library is stuck in a surprising in between state and I just believe it needs to be unified :)

**Comment by prateekmedia** [comment]
All hail to `libadwaita`, coming from v1 and forward.
